### ISSUE TITLE
Time to create the Jenkins channel in the Tekton Slack workspace?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/tekton-client-plugin#180]
Just a topic for the discussion. It could help to have more discussions between Tekton and Jenkins communities, especially w.r.t. interoperability.

CC @MarckK @waveywaves

**Comment by garethjevans** [comment]
should we also have a gitter channel for this @oleg-nenashev ?

**Comment by waveywaves** [comment]
I agree we can start a slack workspace in tekton for jenkins interop
@garethjevans +1 we can start a tekton client plugin channel as well, I'll go ahead and create these
