### ISSUE TITLE
I can't find it in jenkins plugins. where and how can i install this plugin to my jenkins ?

### ISSUE THREAD

**Issue by IamGabrielWu** [jenkinsci/tekton-client-plugin#56]
I can't find it in jenkins plugins. where and how can i install this plugin to my jenkins ?

**Comment by jstrachan** [comment]
its been released now, so you should be able to install it: http://archives.jenkins-ci.org/plugins/tekton-client/

**Comment by waveywaves** [comment]
Closing as the issue is resolved
