### ISSUE TITLE
editing a pipeline loses the configuration 

### ISSUE THREAD

**Issue by jstrachan** [jenkinsci/tekton-client-plugin#92]
if you create a Freestyle project using the tekton client plugin and add the `Tekton: Create Resource (Raw)` build step and configure the input type, input and tekton catalog flag it saves nicely into the `config.xml` inside Jenkins and works fine.

But if you then edit the project the configuration values are not loaded into the UI so you can edit them nicely

**Comment by oleg-nenashev** [comment]
Most likely there is a JEP-200 exception due to PrintStream and Classloader serialization to the disk: https://github.com/jenkinsci/jep/tree/master/jep/200 

```
 private PrintStream consoleLogger;
 private ClassLoader toolClassLoader;
```

**Comment by oleg-nenashev** [comment]
Also, getters are `protected`. Jenkins won't be able to load values for the form binding. LIkely this is the root cause of the described behavior

**Comment by jstrachan** [comment]
got a PR coming real soon - @oleg-nenashev was totally crrect, its the protected getters that cause the issue
